# Generated by Django 3.2.6 on 2021-08-11 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField(max_length=20)),
                ('nama', models.CharField(max_length=40)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tanggal_lahir', models.DateField()),
                ('no_kontak', models.IntegerField(max_length=20)),
                ('padukuhan', models.CharField(choices=[('Wadas', 'Wadas'), ('Paten', 'Paten'), ('Ngemplak Caban', 'Ngemplak Caban'), ('Pangukan', 'Pangukan'), ('Beteng', 'Beteng'), ('Pisangan', 'Pisangan'), ('Dukuh', 'Dukuh'), ('Beran Lor', 'Beran Lor'), ('Josari', 'Josari'), ('Drono', 'Drono'), ('Beran Kidul', 'Beran Kidul'), ('Kebonagung', 'Kebonagung'), ('Jaban', 'Jaban'), ('Denggung', 'Denggung'), ('Bangunrejo', 'Bangunrejo')], max_length=20)),
                ('rt', models.IntegerField(max_length=3)),
                ('rw', models.IntegerField(max_length=3)),
                ('alamat', models.TextField(max_length=100)),
                ('tanggal_input', models.DateField(default=datetime.date.today)),
                ('waktu_input', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Konfirmasi', 'Konfirmasi'), ('Isolasi Mandiri', 'Isolasi Mandiri'), ('Dirawat', 'Dirawat'), ('Sembuh', 'Sembuh'), ('Meninggal', 'Meninggal')], default='Konfirmasi', max_length=25)),
                ('faskes_awal', models.CharField(default='Puskesmas Sleman', max_length=25)),
                ('Rujukan', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
