# Generated by Django 3.2.6 on 2021-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_kontak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warga',
            name='rt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warga',
            name='rw',
            field=models.IntegerField(),
        ),
    ]
