# Generated by Django 3.2.6 on 2021-08-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_auto_20210811_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='jenis_kelamin',
            field=models.CharField(max_length=10),
        ),
    ]
