# Generated by Django 3.2.6 on 2021-08-11 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0004_alter_warga_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='waktu_input',
            field=models.TimeField(default=datetime.time(17, 56, 34, 832807)),
        ),
    ]
