# Generated by Django 3.2.6 on 2021-08-11 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0005_alter_warga_waktu_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='usia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='waktu_input',
            field=models.TimeField(default=datetime.time(19, 38, 23, 424360)),
        ),
    ]
